package data

import androidx.room.Database
import androidx.room.RoomDatabase
import data.example.source.local.ExampleEntityLocal
import data.example.source.local.ExampleDao

/**
 * The Room database for this app.
 *
 * To add a new entity:
 *  1. Create the @Entity class and its @Dao interface in the appropriate feature package.
 *  2. Add the entity class to the [entities] array below.
 *  3. Add an abstract DAO accessor function below.
 *  4. Bump [version] and add a migration in [DatabaseMigration] (or use @AutoMigration).
 *
 * The concrete implementation is generated by Room's KSP processor at build time.
 * Platform-specific database construction (file path, driver) is in [DatabaseFactory].
 */
@Database(
    entities = [ExampleEntityLocal::class],
    version = 1,
    exportSchema = true,
)
abstract class AppDatabase : RoomDatabase() {
    abstract fun exampleDao(): ExampleDao
}
