package data

import androidx.room.Delete
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Transaction
import androidx.room.Update
import kotlinx.coroutines.flow.Flow

/**
 * Interface enforced on all Room entities in this project.
 * Any entity that does not implement this interface cannot be used
 * with BaseDao, enforced at compile time via type constraint.
 */
interface DatabaseObject {
    val id: String
    val seedKey: String?
}

/**
 * Generic base DAO for all Room entities in this project.
 *
 * Room resolves [T] when processing each @Dao subclass, allowing @Insert/@Update/@Delete
 * and their concrete wrappers to be generated once here rather than repeated per entity.
 *
 * @Query operations require hardcoded table names and cannot be generic — subclasses declare
 * them as abstract overrides annotated with @Query, and Room generates the implementations.
 *
 * Methods throw on failure; callers (typically repositories) wrap in [runCatching] where a
 * [Result] return type is appropriate.
 */
abstract class BaseDao<T : DatabaseObject> {
    // *C* reate ---------------------------------------------------------------------------

    /** Insert or replace an entity. Implementation generated by Room. */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    abstract suspend fun upsert(entity: T)

    /** Insert or replace multiple entities. Implementation generated by Room. */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    abstract suspend fun upsertAll(entities: List<T>)

    /** Insert only if absent — silently skips rows that already exist. Implementation generated by Room. */
    @Insert(onConflict = OnConflictStrategy.IGNORE)
    abstract suspend fun insertIfAbsent(entity: T)

    // *R* ead -----------------------------------------------------------------------------

    /** Select all entities from the table. */
    abstract suspend fun findAll(): List<T>

    /** Subclasses annotate the override with @Query; Room generates the implementation. */
    protected abstract suspend fun findByIdOrNull(id: String): T?

    /**
     * Select an entity by id.
     *
     * @throws NoSuchElementException if no entity with [id] exists.
     */
    suspend fun findById(id: String): T = findByIdOrNull(id) ?: throw NoSuchElementException("No entity found with id: $id")

    /**
     * Observes a single entity by its id.
     *
     * @return flow emitting the entity, or null if deleted.
     */
    abstract fun observeById(id: String): Flow<T?>

    /**
     * Observes a single entity by its seed key.
     *
     * @return flow emitting the entity, or null if not found.
     */
    abstract fun observeBySeedKey(seedKey: String): Flow<T?>

    /**
     * Observes all entities as a list.
     *
     * @return flow emitting the full list whenever any row changes.
     */
    abstract fun observeAll(): Flow<List<T>>

    // *U* pdate ---------------------------------------------------------------------------

    /** Update an existing entity. Unlike [upsert], does nothing if the entity is absent. Implementation generated by Room. */
    @Update
    abstract suspend fun update(entity: T)

    /**
     * Find an entity by id, apply a mutation, and save it within a single transaction.
     *
     * Prefer this over [findById] + [update] for field-level mutations.
     *
     * @throws NoSuchElementException if no entity with [id] exists.
     */
    @Transaction
    open suspend fun updateById(
        id: String,
        mutation: T.() -> Unit,
    ) {
        val entity =
            findByIdOrNull(id)
                ?: throw NoSuchElementException("No entity found with id: $id")
        entity.apply(mutation)
        update(entity)
    }

    // *D* elete ---------------------------------------------------------------------------

    /** Delete an entity. Implementation generated by Room. */
    @Delete
    abstract suspend fun delete(entity: T)

    /** Delete all entities in list. Implementation generated by Room. */
    @Delete
    abstract suspend fun deleteAllFrom(entities: List<T>)

    /** Subclasses annotate the override with @Query; Room generates the implementation. */
    abstract suspend fun deleteById(id: String)

    /** Subclasses annotate the override with @Query; Room generates the implementation. */
    abstract suspend fun deleteAll()
}
